# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tsnwifi', ['core','clock'])
    module.source = [
        'model/send-action-frame-application.cc',
        'model/sleep-cycle-application.cc',
        'model/Sta-priority.cc',
        'model/switch-trace-application.cc',
        'helper/wifi-setup.cc',
	'helper/ftm_sync.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'tsnwifi'
    headers.source = [
        'model/send-action-frame-application.h',
        'model/sleep-cycle-application.h',
        'model/Sta-priority.h',
        'model/switch-trace-application.h',
        'helper/wifi-setup.h',
	'helper/ftm_sync.h',
        ]


    bld.ns3_python_bindings()

